Renamed agents to chaos delegates
chaosnative/chaosctl pull request #14
Opened 2022-07-23 19:21 UTC by SarthakJain26

- Renamed agents to chaos delegates in logs, readme
- Updated `create agent` to `connect chaos-delegate`
- Updated `get agents` to `get chaos-delegates`

Signed-off-by: Sarthak Jain <sarthak.jain@harness.io>

2022-07-24 05:55 UTC, Jonsy13 approved these changes

2022-07-24 08:30 UTC, Saranya-jena commented on Usage.md
> +### Minimal steps to connect an chaos delegate
connect a chaos delegate

2022-07-24 08:30 UTC, Saranya-jena commented on Usage.md
> +* To connect an chaos delegate without a project
same here

2022-07-24 08:30 UTC, Saranya-jena commented on Usage_interactive.md
> +### Steps to create an chaos delegate
same here

2022-07-24 08:30 UTC, Saranya-jena commented on Usage_interactive.md
> +- To connect an chaos delegate in a cluster mode
same here

2022-07-24 08:30 UTC, Saranya-jena commented on Usage_interactive.md
> +It can install an chaos delegate in two different modes.
same

2022-07-24 08:30 UTC, Saranya-jena commented on pkg/agent/ops.go
> +		Label: "What's the chaos delegate Name?",
Name -> name

2022-07-24 08:30 UTC, Saranya-jena commented on pkg/agent/ops.go
> +		utils.Red.Println("⛔ Chaos Delegate name cannot be empty. Please enter a valid name.")
Delegate -> delegate

2022-07-24 08:30 UTC, Saranya-jena commented on pkg/cmd/connect/agent.go
> +	#connect an chaos delegate
an -> a

2022-07-24 08:30 UTC, Saranya-jena commented on pkg/cmd/connect/agent.go
> +	#connect an chaos delegate within a project
same

2022-07-24 08:30 UTC, Saranya-jena commented on pkg/cmd/connect/agent.go
> +			utils.Red.Print("\n🚫 Token Generation failed, Chaos Delegate installation failed\n")
Chaos Delegate -> chaos delegate

2022-07-24 08:34 UTC, Saranya-jena commented on pkg/cmd/root/root.go
> +	Short: "ChaosCTL controls the ChaosNative cloud chaos delegate plane",
Should we change this to `Harness Chaos Engineering Cloud`?  @Jonsy13 @SarthakJain26

2022-07-25 06:12 UTC, Jonsy13 commented on pkg/cmd/root/root.go
> +	Short: "ChaosCTL controls the ChaosNative cloud chaos delegate plane",
Yes we should

2022-07-25 07:34 UTC, Saranya-jena requested changes

2022-07-25 07:34 UTC, Saranya-jena commented on pkg/cmd/upgrade/upgrade.go
> +		chaosctl upgrade chaos-delegate --cluster-id="4cc25543-36c8-4373-897b-2e5dbbe87bcf" --project-id="d861b650-1549-4574-b2ba-ab754058dd04" --non-interactive
--cluster-id -> chaos-delegate-id

2022-07-25 07:58 UTC, Saranya-jena approved these changes

2022-07-25 07:59 UTC, merged